# Generated by Django 3.0 on 2025-06-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Device_name', models.CharField(max_length=20, unique=True)),
                ('Device_type', models.CharField(max_length=20)),
                ('Device_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('habitname', models.CharField(max_length=20, unique=True)),
                ('devicename', models.CharField(max_length=20)),
                ('devicetype', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('brightness', models.IntegerField(default=100, null=True)),
                ('temperature', models.IntegerField(default=25, null=True)),
                ('mode', models.CharField(default='cool', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('Log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('devicename', models.CharField(max_length=50)),
                ('devicetype', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Device')),
                ('temperature', models.IntegerField(default=25)),
                ('mode', models.CharField(default='cool', max_length=20)),
            ],
            bases=('app.device',),
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Device')),
            ],
            bases=('app.device',),
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Device')),
                ('brightness', models.IntegerField(default=100)),
            ],
            bases=('app.device',),
        ),
        migrations.CreateModel(
            name='Robotvacuum',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Device')),
                ('mode', models.CharField(default='clean', max_length=20)),
                ('starttime', models.DateTimeField(auto_now_add=True, null=True)),
                ('sweeparea', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=100)),
            ],
            bases=('app.device',),
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Device')),
                ('starttime', models.DateTimeField(auto_now_add=True, null=True)),
                ('mode', models.CharField(default='wash', max_length=20)),
            ],
            bases=('app.device',),
        ),
    ]
